/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kgrech_statcollectior_client_monitor_MemoryChecker */

#ifndef _Included_com_github_kgrech_statcollectior_client_monitor_MemoryChecker
#define _Included_com_github_kgrech_statcollectior_client_monitor_MemoryChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kgrech_statcollectior_client_monitor_MemoryChecker
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jfloat JNICALL Java_com_github_kgrech_statcollectior_client_monitor_MemoryChecker_doGetValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
