/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kgrech_statcollectior_client_monitor_ProcessesChecker */

#ifndef _Included_com_github_kgrech_statcollectior_client_monitor_ProcessesChecker
#define _Included_com_github_kgrech_statcollectior_client_monitor_ProcessesChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kgrech_statcollectior_client_monitor_ProcessesChecker
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_github_kgrech_statcollectior_client_monitor_ProcessesChecker_doGetValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
